-- Demo seed data for Teacher Jobs UZ
-- Run in Supabase SQL Editor to populate sample vacancies

insert into public.vacancies (
  title,
  subject,
  description,
  requirements,
  responsibilities,
  city,
  district,
  salary_min,
  salary_max,
  salary_text,
  employment_type,
  source_type,
  source_name,
  status,
  verified,
  published_at
) values
(
  'Matematika (SAT / Olimpiada) o‘qituvchisi',
  'Matematika',
  'Prezident maktabi va xalqaro olimpiadalarga tayyorlovchi zamonaviy o‘quv markazi kuchli matematika mutaxassisini jamoaga taklif etadi. O‘quvchilarga chuqurlashtirilgan dastur asosida dars o‘tiladi.',
  'Oliy pedagogik ma’lumot, kamida 3 yillik ish tajribasi. Respublika olimpiadalarida g‘olib bo‘lgan shogirdlari bo‘lishi ustunlik beradi.',
  'Darslarni interaktiv tarzda o‘tish, olimpiada masalalarini tahlil qilish, oylik test sinovlarini tashkil etish.',
  'Toshkent',
  'Mirzo Ulug‘bek tumani',
  10000000,
  18000000,
  '10 - 18 mln so‘m',
  'full_time',
  'manual',
  'Prezident ta’lim maskani',
  'published',
  true,
  now() - interval '2 days'
),
(
  'Ingliz tili o‘qituvchisi (IELTS Instructor)',
  'Ingliz tili',
  'Cambridge International School Toshkent filiali uchun xalqaro standartlar asosida dars beruvchi tajribali IELTS o‘qituvchisi kerak.',
  'IELTS 7.5+ yoki CEFR C1 sertifikati, CELTA yoki TESOL diplomi mavjudligi, 2+ yil tajriba.',
  'Akademik ingliz tili darslarini olib borish, writing va speaking bo‘yicha feedback berish.',
  'Toshkent',
  'Yakkasaroy tumani',
  8000000,
  15000000,
  '8 - 15 mln so‘m',
  'full_time',
  'manual',
  'Cambridge International School',
  'published',
  true,
  now() - interval '1 day'
),
(
  'Informatika va IT o‘qituvchisi (Python / Web)',
  'Informatika va IT',
  'Al-Xorazmiy ixtisoslashtirilgan maktabi o‘quvchilarga zamonaviy dasturlash asoslari va algoritmlarni o‘rgatuvchi yosh va iqtidorli o‘qituvchilarni taklif qiladi.',
  'Informatika yoki IT yo‘nalishida oliy ma’lumot, Python dasturlash tili va web asoslarini bilish.',
  'Maktab o‘quvchilariga kompyuter savodxonligi, Python va web development darslarini o‘tish.',
  'Toshkent',
  'Olmazor tumani',
  7000000,
  12000000,
  '7 - 12 mln so‘m',
  'full_time',
  'manual',
  'Al-Xorazmiy ixtisoslashtirilgan maktabi',
  'published',
  true,
  now() - interval '3 days'
),
(
  'Fizika fani o‘qituvchisi',
  'Fizika',
  'Samarqand shahridagi innovatsion xususiy litsey fizika fanini chuqurlashtirilgan va amaliy laboratoriya mashg‘ulotlari bilan o‘tadigan tajribali pedagog qidirmoqda.',
  'Kamida 2 yillik tajriba, fizika qonuniyatlarini tajribalar orqali tushuntira olish, darsga zamonaviy yondashuv.',
  'Dars jadvaliga muvofiq mashg‘ulotlar o‘tish, laboratoriya jihozlari bilan ishlash, o‘quvchilar fan to‘garagini yuritish.',
  'Samarqand',
  'Markaziy tuman',
  6000000,
  10000000,
  '6 - 10 mln so‘m',
  'full_time',
  'manual',
  'Registon intellektual litseyi',
  'published',
  true,
  now() - interval '4 days'
),
(
  'Boshlang‘ich ta’lim o‘qituvchisi',
  'Boshlang‘ich ta'lim',
  'Farg‘ona shahridagi "Smart Kids" xususiy maktabiga 1-4 sinf o‘quvchilari uchun mehribon, sabrli va bolalar psixologiyasini yaxshi tushunadigan ustoz zarur.',
  'Boshlang‘ich ta’lim mutaxassisligi bo‘yicha diplom, toza va chiroyli husnixat, bolalar bilan ishlashda kamida 1 yil tajriba.',
  'Boshlang‘ich sinf fanlarini sifatli o‘rgatish, ota-onalar bilan muntazam muloqot, tarbiyaviy soatlar o‘tkazish.',
  'Farg‘ona',
  'Shaharmarkaz',
  5000000,
  8000000,
  '5 - 8 mln so‘m',
  'full_time',
  'manual',
  'Smart Kids xususiy maktabi',
  'published',
  false,
  now() - interval '5 days'
),
(
  'Kimyo va Biologiya fani o‘qituvchisi (Tibbiyot litseyi)',
  'Kimyo',
  'Buxoro shahridagi ixtisoslashtirilgan tibbiyot litseyi DTM imtihonlariga tayyorlovchi kuchli kimyo-biologiya o‘qituvchisini ishga taklif qiladi.',
  'Oliy ma’lumot, 1- yoki oliy toifa, DTM test formatini chuqur bilish.',
  'DTM va xalqaro dasturlar bo‘yicha darslar o‘tish, test sinovlari tuzish va tahlil qilish.',
  'Buxoro',
  'Buxoro shahar',
  6000000,
  9500000,
  '6 - 9.5 mln so‘m',
  'full_time',
  'manual',
  'Buxoro Ixtisoslashgan Tibbiyot Litseyi',
  'published',
  true,
  now() - interval '6 days'
);
